[package]
name = "crispy-player"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
clap = "2.33.0"
# raster = { git = "https://github.com/kosinix/raster.git" }
raster = "0.2.0"
